[[constraint]]
  version = "v1.0.0"
  name = "github.com/bullettrain-sh/bullettrain-go-git"

[[constraint]]
  version = "v1.0.0"
  name = "github.com/bullettrain-sh/bullettrain-go-golang"

[[constraint]]
  version = "v1.0.0"
  name = "github.com/bullettrain-sh/bullettrain-go-nodejs"

[[constraint]]
  version = "v1.0.0"
  name = "github.com/bullettrain-sh/bullettrain-go-php"

[[constraint]]
  version = "v1.0.0"
  name = "github.com/bullettrain-sh/bullettrain-go-python"

[[constraint]]
  version = "v1.0.0"
  name = "github.com/bullettrain-sh/bullettrain-go-ruby"

[[constraint]]
  name = "github.com/bullettrain-sh/bullettrain-go-openvpn"
