[[constraint]]
  version = "v0.7"
  name = "github.com/bullettrain-sh/bullettrain-go-git"

[[constraint]]
  version = "v0.7"
  name = "github.com/bullettrain-sh/bullettrain-go-golang"

[[constraint]]
  version = "v0.7"
  name = "github.com/bullettrain-sh/bullettrain-go-nodejs"

[[constraint]]
  version = "v0.7"
  name = "github.com/bullettrain-sh/bullettrain-go-php"

[[constraint]]
  version = "v0.7"
  name = "github.com/bullettrain-sh/bullettrain-go-python"

[[constraint]]
  version = "v0.7"
  name = "github.com/bullettrain-sh/bullettrain-go-ruby"
